#!/bin/bash
# PreToolUse(Edit|Write): refuse hand-edits to the XcodeGen-generated project.
#
# ProxyLens.xcodeproj is generated from project.yml and committed. scripts/quality.sh
# regenerates it in a temp directory and diffs, so hand edits fail the gate.

set -uo pipefail

file_path="$(jq -r '.tool_input.file_path // empty')"

[[ -n "$file_path" ]] || exit 0

case "$file_path" in
    *ProxyLens.xcodeproj/*)
        cat >&2 <<'MESSAGE'
ProxyLens.xcodeproj is generated by XcodeGen from project.yml and must not be edited by hand.
check_xcodegen_sync in scripts/quality.sh regenerates the project and diffs it, so manual edits
fail `./scripts/quality.sh full` and `ci`.

Edit project.yml instead, then run: xcodegen generate
MESSAGE
        exit 2
        ;;
esac

exit 0
